### ISSUE TITLE
duplicate record key

### ISSUE THREAD

**Issue by joggerjoel** [gentics/mesh-musetech-example#3]
I tried to populate using the importer. But, it stopped with duplicate key ERROR. 

**Environment**
openjdk version "1.8.0_232"
node v8.10.0
Ubuntu 18.04.2 LTS

**Server Build**
#run as sudo
>cd ~/mesh
>mvn clean install -Denv.JAVA_1_8_HOME=$JAVA_HOME -DskipTests -Dskip.unit.tests -Dskip.performance.test s -Dskip.cluster.tests -Dmaven.javadoc.skip=true
>chown username.username -R ~/mesh

**Server Run**
#run as user
>cd ~/mesh/demo/target
>java -jar mesh-demo-1.3.3-SNAPSHOT.jar

**Client Importer Build**
>cd ~/mesh-musetech-example/importer
> ./mvnw -B -U clean package
> cp -rf data target

**Client Importer Run**
>cd ~/mesh-musetech-example/importer/target
>java -jar mesh-musetech-importer-0.0.1-SNAPSHOT.jar

**Client Output**

`Dec 25, 2019 12:01:49 PM com.gentics.mesh.musetech.importer.impl.ImporterImpl    INFO: Created screen screen-1                                                    com.gentics.mesh.rest.client.MeshRestClientMessageException: Error:500 in POST / api/v1/musetech/nodes/fd58237c79d64bf198237c79d6bbf107 : Internal Server Error I nfo: Internal error occurred.                                                            at com.gentics.mesh.rest.client.impl.MeshOkHttpRequestImpl.throwOnError( MeshOkHttpRequestImpl.java:169)                                                          at com.gentics.mesh.rest.client.impl.MeshOkHttpRequestImpl.mapResponse(M eshOkHttpRequestImpl.java:137)                                                           at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.on Success(SingleMap.java:57)                                                               at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess (SingleCreate.java:67)                                                                   at com.gentics.mesh.rest.client.impl.MeshOkHttpRequestImpl$2.onResponse( MeshOkHttpRequestImpl.java:122)                                                          at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)                         at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor. java:1149)                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor .java:624)                                                                               at java.lang.Thread.run(Thread.java:748)
`

`Dec 25, 2019 12:01:49 PM com.gentics.mesh.musetech.importer.impl.ImporterImpl    INFO: Created screen screen-1                                                    com.gentics.mesh.rest.client.MeshRestClientMessageException: Error:500 in POST / api/v1/musetech/nodes/fd58237c79d64bf198237c79d6bbf107 : Internal Server Error I nfo: Internal error occurred.                                                            at com.gentics.mesh.rest.client.impl.MeshOkHttpRequestImpl.throwOnError( MeshOkHttpRequestImpl.java:169)                                                          at com.gentics.mesh.rest.client.impl.MeshOkHttpRequestImpl.mapResponse(M eshOkHttpRequestImpl.java:137)                                                           at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.on Success(SingleMap.java:57)                                                               at io.reactivex.internal.operators.single.SingleCreate$Emitter.onSuccess (SingleCreate.java:67)                                                                   at com.gentics.mesh.rest.client.impl.MeshOkHttpRequestImpl$2.onResponse( MeshOkHttpRequestImpl.java:122)                                                          at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)                         at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor. java:1149)                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor .java:624)                                                                               at java.lang.Thread.run(Thread.java:748)
`

**Server Output**

`
12:01:49.104 [] ERROR [vert.x-worker-thread-5] [c.g.m.g.OrientDBDatabase] - com.orientechnologies.orient.core.storage.ORecordDuplicatedException:  Cannot index record #742:19: found duplicated key '1c51487f8e8043c291487f8e8053c2c1' in index 'MeshVertexImpl' previously assigned to the record  #753:1                                                                                                                                                   DB name="storage" INDEX=MeshVertexImpl RID=#753:1                                                                                         12:01:49.107 [] ERROR [vert.x-worker-thread-18] [c.g.m.g.OrientDBDatabase] - com.orientechnologies.orient.core.storage.ORecordDuplicatedException : Cannot index record #743:19: found duplicated key 'fd58237c79d64bf198237c79d6bbf107' in index 'MeshVertexImpl' previously assigned to the recor d #738:2                                                                                                                                                  DB name="storage" INDEX=MeshVertexImpl RID=#738:2                                                                                         12:01:49.109 [] ERROR [vert.x-eventloop-thread-15] [c.g.m.r.r.FailureHandler] - Error for request in path: /api/v1/musetech/nodes/fd58237c79d64bf 198237c79d6bbf107                                                                                                                                 12:01:49.111 [] ERROR [vert.x-eventloop-thread-15] [c.g.m.r.r.FailureHandler] - Error:                                                            com.gentics.mesh.core.rest.error.GenericRestException: 500 Internal Server Error error_internal params {}                                                 at com.gentics.mesh.core.rest.error.Errors.error(Errors.java:86)                                                                                  at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:368)                                                                        at com.gentics.mesh.core.verticle.handler.HandlerUtilities.eventAction(HandlerUtilities.java:337)                                                 at com.gentics.mesh.core.verticle.handler.HandlerUtilities.eventAction(HandlerUtilities.java:327)                                                 at com.gentics.mesh.core.verticle.handler.HandlerUtilities.lambda$createOrUpdateElement$5(HandlerUtilities.java:166)                              at com.gentics.mesh.graphdb.OrientDBDatabase.tx(OrientDBDatabase.java:343)                                                                        at com.gentics.mesh.core.verticle.handler.HandlerUtilities.syncTx(HandlerUtilities.java:244)                                                      at com.gentics.mesh.core.verticle.handler.HandlerUtilities.createOrUpdateElement(HandlerUtilities.java:145)                                       at com.gentics.mesh.core.verticle.handler.HandlerUtilities.updateElement(HandlerUtilities.java:129)                                               at com.gentics.mesh.core.endpoint.handler.AbstractCrudHandler.handleUpdate(AbstractCrudHandler.java:84)                                           at com.gentics.mesh.core.endpoint.node.NodeEndpoint.lambda$addUpdateHandler$16(NodeEndpoint.java:431)                                             at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)                                               at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)                                                                  at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)                                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)                                                          at java.lang.Thread.run(Thread.java:748)
`

**Comment by joggerjoel** [comment]
I manually changed the original uuid: fd58237c79d64bf198237c79d6bbf107 to a different uuid for both about.en.json and about.de.json. This seemed to fixed.

`
Dec 25, 2019 1:44:40 PM com.gentics.mesh.musetech.importer.impl.ImporterImpl                                                                      INFO: Created screen screen-2                                                                                                                     Import done. Took: 6404[ms]
`

**Comment by Jotschi** [comment]
I have updated the importer. Maybe the change in the importer will resolve the issue for you. So far I have never seen the duplicate key error during import. Please re-open the issue if you feel the problem needs to be looked at again. Thanks.
